name:  'riverpod_countup'
description: "A new Flutter project."
 
publish_to: 'none' 
version: 1.0.0+1
 
environment:
 sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  material_floating_search_bar_2: ^0.5.0
  material_floating_search_bar: ^0.3.7
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.2
  cloud_firestore: ^4.11.0
  firebase_core: ^2.19.0
  firebase_storage: ^11.3.1
  firebase_auth: ^4.11.1
  firebase_messaging: ^14.7.1
  firebase_analytics: ^10.6.1
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.5
  google_fonts: ^4.0.3
  pull_to_refresh: ^2.0.0
  image_cropper: ^1.4.1
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  clipboard: ^0.1.3
  flutter_launcher_icons: ^0.13.0
  flash: ^2.0.5+1
  uuid: ^3.0.5
  image_picker: ^0.8.4+11
  flutter_svg: ^2.0.5
  firebase_crashlytics: ^3.3.5
  fluttertoast: ^8.2.2
  http: ^0.13.5
  flutter_dotenv: ^5.1.0
  algolia: ^1.1.2
  freezed_annotation: ^2.1.0
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.1
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.18.6
  wechat_assets_picker: ^8.6.3
  intl: ^0.18.1
  connectivity_plus: ^4.0.2
  material_color_utilities: ^0.5.0
  audioplayers: ^5.2.0

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.1

dependency_overrides:
   intl: ^0.18.0-nullsafety.2
 
flutter:
  uses-material-design: true
  #  追加
  # assets:
  #   - assets/sounds/
# - sounds/DiskWriter.mp3
# - sounds/HC85.mp3
# - sounds/gameWatch.mp3


#  追加
flutter_icons:       
  android: true
  ios: true
  image_path: "assets/images/minchi.png"

# 20230824雅也追加作成
  # assets:
  #   - .env
